services:

    jira:
        build: ./.docker
        environment:
            - JVM_SUPPORT_RECOMMENDED_ARGS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dquickreload.dirs=/opt/app
        ports:
            - 5005:5005
            - 8080:8080
        volumes:
            - ./target/quickreload:/opt/app
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=jira
            - POSTGRES_PASSWORD=jira
            - POSTGRES_DB=jira
            - LANG=C
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U jira"]
            interval: 10s
            timeout: 5s
            retries: 5
