package net.congstar.jira.plugins.planningpoker;

import com.atlassian.crowd.embedded.api.User;
import com.atlassian.jira.issue.Issue;
import com.atlassian.jira.plugin.webfragment.conditions.AbstractJiraCondition;
import com.atlassian.jira.plugin.webfragment.model.JiraHelper;

/**
 * Only display the planning poker web element for issues of the type 'Story' which is generated by JIRA Agile.
 */
public class StoryTypeCondition extends AbstractJiraCondition {

    @Override
    public boolean shouldDisplay(User user, JiraHelper jiraHelper) {
        Issue currentIssue = (Issue) jiraHelper.getContextParams().get("issue");
        return currentIssue.getIssueTypeObject().getName().equals("Story");
    }

}
