package net.congstar.jira.plugins.scrumpoker;

import com.atlassian.jira.issue.Issue;
import com.atlassian.jira.plugin.webfragment.conditions.AbstractWebCondition;
import com.atlassian.jira.plugin.webfragment.model.JiraHelper;
import com.atlassian.jira.user.ApplicationUser;

/**
 * Only display the planning poker web element for issues of the type 'Story' which is generated by JIRA Agile.
 */
public class StoryTypeCondition extends AbstractWebCondition {

    @Override
    public boolean shouldDisplay(ApplicationUser applicationUser, JiraHelper jiraHelper) {
        Issue currentIssue = (Issue) jiraHelper.getContextParams().get("issue");
        return currentIssue != null && currentIssue.getIssueTypeObject().getName().equals("Story");
    }

}
