# jekyll configuration
# --------------------
highlighter: rouge
markdown: kramdown

# site configuration
# ------------------
title: Scrum Poker for Jira

# url configuration
# -----------------
github_url: https://github.com/codescape/jira-scrum-poker
marketplace_url: https://marketplace.atlassian.com/apps/1218884/scrum-poker?hosting=server&tab=overview
servicedesk_url: https://codescape.atlassian.net/servicedesk

# contact data
# ------------
contact_mail: support@codescape.atlassian.net
